### ISSUE TITLE
import to eclipse not working with Gradle 3.1

### ISSUE THREAD

**Issue by rasenderhase** [scalding/gradle-waroverlay-plugin#8]
as of Gradle 3.1 the project import is not working any more:

`org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: HierarchicalEclipseProject.getIdentifier().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
    at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:34)
    at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:342)
    at com.sun.proxy.$Proxy40.getIdentifier(Unknown Source)
    at com.gradleware.tooling.toolingclient.internal.deduplication.EclipseProjectDeduplicator$RenamedEclipseProjectTracker.<init>(EclipseProjectDeduplicator.java:87)
    at com.gradleware.tooling.toolingclient.internal.deduplication.EclipseProjectDeduplicator.deduplicate(EclipseProjectDeduplicator.java:38)
    at com.gradleware.tooling.toolingclient.internal.deduplication.DeduplicatingGradleConnection$DeduplicatingEclipseModelBuilder$DeduplicatedModelResults.iterator(DeduplicatingGradleConnection.java:126)
    at com.gradleware.tooling.toolingmodel.repository.internal.ModelResultsConverter$ConvertedModelResults.iterator(ModelResultsConverter.java:67)
    at org.eclipse.buildship.core.workspace.internal.SynchronizeCompositeBuildJob.fetchEclipseProjects(SynchronizeCompositeBuildJob.java:77)
    at org.eclipse.buildship.core.workspace.internal.SynchronizeCompositeBuildJob.runToolingApiJob(SynchronizeCompositeBuildJob.java:65)
    at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
    at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:63)
    at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
`

I think it's because they have removed the method `HierarchicalEclipseProject.getIdentifier()` in Gradle 3.1. Where/Why is the plugin calling this method?

See also https://docs.gradle.org/3.1/release-notes#tooling-api-models-have-missing-dependency-information-when-importing-composite-builds

**Comment by scalding** [comment]
Could you try running your build from the command line and see if the same problem exhibits itself? When I do so, using a gradle 3.1 wrapper, I'm not able to recreate. It looks like you are running this in Eclipse, and I'm wondering if that might be the problem. Thanks

**Comment by rasenderhase** [comment]
Hi, you are right. It's working in the console. And now even in Eclipse. ❓ ❓ ❓

**Comment by scalding** [comment]
I tend to blame [https://en.wikipedia.org/wiki/Gremlin]. If you continue to have problems, you might open a ticket with the Eclipse project, or the maintainer of the gradle plugin for Eclipse.
